---
name: Padre-Plugin-CommandLine
version: 0.01
author:
  - 'Gabor Szabo <szabgab@gmail.com>'
abstract: vi and emacs in Padre ?
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  Padre::Plugin::CommandLine:
    file: lib/Padre/Plugin/CommandLine.pm
    version: 0.01
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
